Bring collect_config back into backup
- Include the script again in the main script.
- Move all files/dirs into external lists.
- Iterate over exisiting files/dirs.

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -44,12 +44,47 @@ check_bitrot() {
 }
 
 collect_config() {
-	if "${_resourcedir}"/collect_config ; then
-		printf "${_good}[2/5] ----- Collected configurations.${_rset}\n\n"
-	else
-		printf "${_fail}[2/5] ----- Collecting configurations failed.${_rset}\n\n"
-		exit 1
-	fi
+	# collect stuff in ~/.config/
+	printf "%s\n" "---> Start collecting configurations:"
+	_configdir="${_dotdir}"/configurations
+	mkdir -p "${_configdir}" \
+		&& printf "${_good}%s${_rset}\n" "Created ${_configdir}" \
+		|| exit 1
+
+	mkdir -p "${_configdir}"/.config || exit 1
+	configlist="${_resourcedir}"/list-config.txt
+	nr=$(grep -c '' "$configlist")
+	i=0
+
+	while IFS= read -r c ; do
+		if [ -e "$HOME"/.config/"$c" ] ; then
+			i=$((i+1))
+			cp -R "$c" "${_configdir}"/.config \
+				&& printf "${_good}%s${_rset}\n" "collected $i/${nr} ($HOME/.config/$c)" \
+				|| exit 1
+		else
+			printf "${_fail}%s${_rset}\n" "$c does not exist."
+		fi
+	done < "$configlist"
+
+	# collect stuff in ~/
+	homelist="${_resourcedir}"/list-home.txt
+	nr=$(grep -c '' "$homelist")
+	i=0
+
+	while IFS= read -r h ; do
+		if [ -e "$HOME"/"$h" ] ; then
+			i=$((i+1))
+			cp -R "$c" "${_configdir}" \
+				&& printf "${_good}%s${_rset}\n" "collected $i/${nr} ($HOME/$h)" \
+				|| exit 1
+		else
+			printf "${_fail}%s${_rset}\n" "$c does not exist."
+		fi
+	done < "$homelist"
+
+	# collect just the config from ~/.ssh/
+	mkdir -p "${_configdir}"/.ssh && cp "$HOME"/.ssh/config "${_configdir}"/.ssh/config
 }
 
 collect_privconfig() {
