Bring collect_installs back into backup

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -97,11 +97,25 @@ collect_privconfig() {
 }
 
 collect_installs() {
-	if "${_resourcedir}"/collect_installs ; then
-		printf "${_good}[4/5] ----- Created list of installed packages.${_rset}\n\n"
+	printf "%s\n" "---> Start collecting installed packages:"
+	_installdir="${_dotdir}"/installed_packages
+	mkdir -p "${_installdir}" \
+		&& printf "${_good}%s${_rset}\n" "Created ${_installdir}" \
+		|| exit 1
+
+	if [ "$(uname -s)" = "OpenBSD" ] ; then
+		pkg_info -tz >> "${_installdir}"/openbsd_pkgs.txt \
+			&& printf "${_good}%s${_rset}\n" "collected OpenBSD packages" \
+			|| exit 1
+	elif [ "$(awk -F "(\"| )" 'NR == 1 { print $2 }' /etc/os-release)" = "Fedora" ] ; then
+		dnf history userinstalled >> "${_installdir}"/fedora_pkgs.txt \
+			&& printf "${_good}%s${_rset}\n" "collected Fedora packages" \
+			|| exit 1
+		flatpak list --app >> "${_installdir}"/flatpaks.txt \
+			&& printf "${_good}%s${_rset}\n" "collected Flatpaks packages" \
+			|| exit 1
 	else
-		printf "${_fail}[4/5] ----- Creating list of installed packages failed.${_rset}\n\n"
-		exit 1
+		printf "${_fail}%s${_rset}\n" "OS is unknown. Aborting..." && exit 1
 	fi
 }
 
